### ISSUE TITLE
Client side error when generating pairs

### ISSUE THREAD

**Issue by nickserv** [paircolumbus/pairs#29]
I am seeing the following error on the client side:

```
Exception in template helper: TypeError: Cannot read property 'trim' of undefined
```

This error seems to prevent regenerating pairs until the existing pairs (if any) are cleared.

**Comment by cartoloupe** [comment]
@nicolasmccurdy I saw this error too in the full-screen-view branch, and fixed it with the following: https://github.com/paircolumbus/pairs/blob/full-screen-view/client/helpers.js#L9-L14

``` javascript
Template.registerHelper('avatarFor', function (email) {
  if (email == null){
    email = 'meteor@meteor.com';
  }
  return Gravatar.imageUrl(email, { size: 32 });
});
```

I think the issue arises from having a null email?

Re: the behavior of the generate pairs button, that's the intended behavior that I had in mind. Generate pairs will only generate pairs from the unpaired pool, but won't re-shuffle any existing pairs. This is from a workflow where you have several pairs set and are trying to rearrange others, and you would remove the pairs you wanted and regenerate just those again.

**Comment by nickserv** [comment]
Nice! I figured out that there's a slightly simpler way to avoid this error. If the Gravatar API is not given a hash (which is how you look up a gravatar based on someone's email address), it just gives back the default image. If we make sure that a string is always passed to the Gravatar library, it will work even if the string in empty (in which case it will default to the empty string).

``` javascript
Template.registerHelper('avatarFor', function (email) {
  return Gravatar.imageUrl(email || '', { size: 32 });
});
```

> the behavior of the generate pairs button, that's the intended behavior that I had in mind...

I see, that makes sense. I agree with this behavior, though I would like to see if we can make this more obvious in the UI.
