### ISSUE TITLE
remove the unpaired but don't delete them

### ISSUE THREAD

**Issue by cartoloupe** [paircolumbus/pairs#36]
> Do you think it would be useful to offer the ability to delete unpaired people from the pairs page?

Consider this structure: 
- [x] ability to remove unpaired people from pairings views
- [x] this will not delete them
- [x] deleting will still be possible on the people view
- [x] this would mean that there would be an additional "bin" to put people in -- one that indicates that they are or are not participating in the current pairings

**Comment by nickserv** [comment]
Interesting. So you would mainly be remove someone from an event but without deleting their account, right? I think this would be especially useful for the future of the app, where we might have multiple organizations using the same instance of the pairs app for different events. This way, if you happen to already be using pairs for something else, you can just sign yourself into a different organization or event.

**Comment by cartoloupe** [comment]
Yes, I agree. It would also help in situations where people participate in pairs, but not necessarily at every pair event. Having this structure would also help in keeping attendance and pairing records over time.

**Comment by nickserv** [comment]
Good point, agreed.

**Comment by cartoloupe** [comment]
addressed by #46
