### ISSUE TITLE
Toggle skills on both pages

### ISSUE THREAD

**Issue by nickserv** [paircolumbus/pairs#38]
Instead of having a separate fullscreen template, it should be simpler to have per users toggles on displaying skills on either page.

**Comment by cartoloupe** [comment]
### a user story

As people come to the event, the organizer will ask them if they have signed in before.

**"Do you see your name on the screen?"**
**if yes:** organizer clicks name, marking them to be a participant in today's event
**if no:** organizer clicks 'add person', fills in name/email/teaching/learning, and saves, this marks the new entry to be a participant in today's event

This seems like a change in the people view, toggling skills and/or presenting people in a more concise manner.
