### ISSUE TITLE
Sign in workflow

### ISSUE THREAD

**Issue by cartoloupe** [paircolumbus/pairs#39]
As people come to the event, the organizer will ask them if they have signed in before.

"Do you see your name on the screen?"
if yes: organizer clicks name, marking them to be a participant in today's event
if no: organizer clicks 'add person', fills in name/email/teaching/learning, and saves, this marks the new entry to be a participant in today's event

This seems like a change in the people view, toggling skills and/or presenting people in a more concise manner.

**Comment by nickserv** [comment]
Should we mark this as a duplicate in favor of #38, or are these two different issues?

**Comment by cartoloupe** [comment]
Yes, I agree, this is pretty much a duplicate. Closing.
