### ISSUE TITLE
deploy to public host

### ISSUE THREAD

**Issue by cartoloupe** [paircolumbus/pairs#47]
this will allow `pairs` to be accessed by any administrator, as opposed to running on one of their local machines;
##### this requires:

~~\- [ ] admin access/login~~
~~\- [ ] accessing site without logging in will allow view on the pairs page~~

**Comment by cartoloupe** [comment]
- currently deployed to [pairs.meteor.com](pairs.meteor.com)
- currently anyone can add themselves and see all pages
- this might work out better because it eliminates the bottleneck of an admin entering participants as they walk in

**Comment by nickserv** [comment]
So right now the deployed app has no admin features?

**Comment by cartoloupe** [comment]
Yes, no admin features yet; those are called out in #33 and #45
