### ISSUE TITLE
update accessible actions for users not signed in

### ISSUE THREAD

**Issue by cartoloupe** [paircolumbus/pairs#55]
https://github.com/paircolumbus/pairs/pull/49 now allows an admin user to sign in and manage pairs. There are still some actions available to public users that should not be:
- [x] random pairs button
- [x] clear pairs button
- [x] save pairs button

maybe these should remain accessible:
- [x] remove pair button
- [x] ability to pair

There are also some actions that should be accessible, but are currently not:
- [x] add person
- [x] marking oneself as away/here

**Comment by nickserv** [comment]
How would we track the user for "marking oneself as away/here"? Would everyone need an account for this?

**Comment by cartoloupe** [comment]
I'm thinking that users would be able to either add themselves, or search for their person, and then mark themself 'here'.

Everyone wouldn't necessarily need an account for this; but there would have to be a public search and ability to toggle the 'away/here' flag.

Pushing up some search logic on this branch; not sure whether to continue rolling own, or to use a search package.
