### ISSUE TITLE
Create an about page

### ISSUE THREAD

**Issue by jaybobo** [paircolumbus/pairs#70]
Create an about page thats accessible to users either from the header or footer of the pairs index page.

The page should be styled per the site style guidelines and include the following:
- about the application and its purpose
- its license

**Comment by andpickens** [comment]
Mary & Andrea are going to work on this.

**Comment by cartoloupe** [comment]
- [x] page and route set up in https://github.com/paircolumbus/pairs/pull/82
- [x] need license information
- [x] need link/button in header/footer of index page

**Comment by jimcavoli** [comment]
License feels like something that should be discussed...any opposition to MIT?

**Comment by jimcavoli** [comment]
PR #93 includes the changes to MIT-license the app, assuming that's the route we'd like to go, but it's there in its own PR so we can merge/discuss separately.
