### ISSUE TITLE
Create a Contributing page

### ISSUE THREAD

**Issue by jaybobo** [paircolumbus/pairs#73]
Create a Contributing page thats accessible to users either from the header or footer of the pairs index page.

The page should be styled per the site style guidelines and include the instructions that explain how to contribute to the project.
- how to submit a pull request
- how to create an issue
- how to request a feature

Example: http://jekyllrb.com/docs/contributing/

**Comment by SethPinckney** [comment]
Michael / Seth

**Comment by cartoloupe** [comment]
- [x] page and route setup in https://github.com/paircolumbus/pairs/pull/78
- [x] more page content in https://github.com/paircolumbus/pairs/pull/79
